<?php

namespace PHPSTORM_META
{
#region autogenerated services for module salescenter


	registerArgumentsSet(
		'bitrix_salescenter_locator_codes',
		'salecenter.component.paysystem',
		'salecenter.integration.salemanager',
	);

	expectedArguments(\Bitrix\Main\DI\ServiceLocator::get(), 0, argumentsSet('bitrix_salescenter_locator_codes'));

	override(
		\Bitrix\Main\DI\ServiceLocator::get(0),
		map([
			'salecenter.component.paysystem' => \Bitrix\SalesCenter\Component\PaySystem::class,
			'salecenter.integration.salemanager' => \Bitrix\SalesCenter\Integration\SaleManager::class,
		]),
	);


#endregion

}
