<?php

namespace PHPSTORM_META
{
#region autogenerated services for module signmobile


	registerArgumentsSet(
		'bitrix_signmobile_locator_codes',
		'signmobile.container',
			'signmobile.service.event',
			'signmobile.repository.notification',
			'signmobile.repository.notification.priority.queue',
	);

	expectedArguments(\Bitrix\Main\DI\ServiceLocator::get(), 0, argumentsSet('bitrix_signmobile_locator_codes'));

	override(
		\Bitrix\Main\DI\ServiceLocator::get(0),
		map([
			'signmobile.container' => \Bitrix\SignMobile\Service\Container::class,
				'signmobile.service.event' => \Bitrix\SignMobile\Service\EventService::class,
				'signmobile.repository.notification' => \Bitrix\SignMobile\Repository\NotificationRepository::class,
				'signmobile.repository.notification.priority.queue' => \Bitrix\SignMobile\Repository\NotificationQueueRepository::class,
		]),
	);


#endregion

}